name: bacaloca
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - img/file.png
    - img/logo.png
    - img/seni.jpg
    - img/NUNCHI.jpg
    - img/bocah.png
    - img/berhasil.png
    - img/gaada.png
    - img/logout.png

